<?xml version="1.0"?>
<package format="3">
  <name>fr3_sim</name>
  <version>0.0.0</version>
  <description>The fr3_sim package</description>

  <maintainer email="guilhem@todo.todo">guilhem</maintainer>
  <license>TODO</license>

  <!-- build tool -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- core dependencies -->
  <depend>rclcpp</depend>
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>trajectory_msgs</depend>
  <depend>control_msgs</depend>

  <!-- control / state publisher -->
  <depend>controller_manager</depend>
  <depend>joint_state_controller</depend>
  <depend>robot_state_publisher</depend>

  <!-- MoveIt 2 -->
  <depend>moveit_core</depend>
  <depend>moveit_ros_perception</depend>
  <depend>moveit_ros_planning_interface</depend>

  <!-- plugins -->
  <depend>pluginlib</depend>

  <!-- visualization -->
  <depend>interactive_markers</depend>

  <!-- custom service -->
  <depend>rosidl_default_generators</depend>
  <depend>rosidl_default_runtime</depend>

  <!-- Testing (optional) -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
